
// Describes the API keys, labels, validations, and optional features for each resource kind.
// Shared create/edit/show/index pages read this instead of hard-coding per-resource branches.
export const RESOURCE_CONFIG = {
  characters: {
    articleFallback: 'A character page waiting for story details.',
    backLabel: 'Back to characters',
    collectionTitle: 'My Characters',
    editEyebrow: 'Edit character',
    formKey: 'character',
    hasImages: true,
    imageLegend: 'Character images',
    introPlaceholder: 'Write a short introduction for this character.',
    label: 'Character',
    loadingLabel: 'character',
    path: 'characters',
  },
  factions: {
    articleFallback: 'A faction page waiting for organizational details.',
    backLabel: 'Back to factions',
    collectionTitle: 'My Factions',
    editEyebrow: 'Edit faction',
    formKey: 'faction',
    hasFamilies: true,
    hasImages: true,
    imageLegend: 'Faction images',
    needsLeaderCharacter: true,
    needsUniverse: true,
    introPlaceholder: 'Write a short introduction for this faction.',
    label: 'Faction',
    loadingLabel: 'faction',
    path: 'factions',
  },
  families: {
    articleFallback: 'A family page waiting for lineage details.',
    backLabel: 'Back to families',
    collectionTitle: 'My Families',
    editEyebrow: 'Edit family',
    formKey: 'family',
    hasOptionalFaction: true,
    hasImages: true,
    imageLegend: 'Family images',
    needsLeaderCharacter: true,
    needsUniverse: true,
    introPlaceholder: 'Write a short introduction for this family.',
    label: 'Family',
    loadingLabel: 'family',
    path: 'families',
  },
  family_trees: {
    articleFallback: 'A family tree waiting for layout details.',
    backLabel: 'Back to families',
    collectionTitle: 'My Family Trees',
    editEyebrow: 'Edit family tree',
    formKey: 'family_tree',
    label: 'Family Tree',
    loadingLabel: 'family tree',
    path: 'family_trees',
  },
  universes: {
    articleFallback: 'A universe page waiting for lore details.',
    backLabel: 'Back to universes',
    collectionTitle: 'My Universes',
    editEyebrow: 'Edit universe',
    formKey: 'universe',
    hasImages: true,
    imageLegend: 'Universe images',
    introPlaceholder: 'Write a short introduction for this universe.',
    label: 'Universe',
    loadingLabel: 'universe',
    path: 'universes',
  },
  worlds: {
    articleFallback: 'A world page waiting for lore details.',
    backLabel: 'Back to worlds',
    collectionTitle: 'My Worlds',
    editEyebrow: 'Edit world',
    formKey: 'world',
    hasImages: true,
    imageLegend: 'World images',
    introPlaceholder: 'Write a short introduction for this world.',
    label: 'World',
    loadingLabel: 'world',
    path: 'worlds',
  },
}
